# -*- coding: utf-8 -*-


"""Trabalho CalculoNumerico - Guilherme_Abreu_Alves.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZxjycpIm_2ehHGIWK6CWop4gvaKLaDtv
"""

import numpy as np 

print('Aluno: Guilherme Abreu Alves')
print('Trabalho 1 - Cálculo numérico')
print(' ')

# Questão 1)
print('Questão 1)','Matriz A e vetor independete b:')
print(' ')
Ma = np.array([[1, 0, 2, 3, 2], [1, 1, 1, 2, 1], [1, 2, 1, 1, 2], [0, 1, 2, 2, 3], [2, 1, 0, 1, 1]])
Mb = np.array([27, 23, 31, 31, 22])
A = [[1,0,2,3,2], [1,1,1,2,1], [1,2,1,1,2], [0,1,2,2,3], [2,1,0,1,1] ]
b = [27,23,31,31,22]

print('  Matriz A',' ')
print(Ma)
print(' ')
print('  Vetor independente b',' ')
print(Mb)
print(' ')

# Questão 2)
print('Questão 2)','Critério das linhas:') 
print(' ')
n = len(A)
alpha = [] 
for i in range(n):
  soma = 0
  for j in range(n):
    if i != j:
      soma += A[i][j]
  soma  = soma/A[i][i]
  alpha.append(soma)
  print('	α({}) = {}'.format(i, alpha[i]) )
  print('')
if max(alpha) < 1:
  print('Os métodos de Gauss-Jacobi e Gauss-Seidel são convergentes!')
else:
  print('Os métodos de Gauss-Jacobi e Gauss-Seidel não são convergentes!')
print('')

print('Questão 3)','Decomposição LU')
print(' ')
def I(n):
    I = []  
    for i in range(0,n):
      linha = [0]*n   
      linha[i] = 1    
      I.append(linha) 
    return I

def fatoraLU(A):
    n = len(A) 
    L = I(n)
    for k in range(0, n-1):
      for i in range(k+1,n):
        m = -A[i][k]/A[k][k]
        L[i][k] = -m
        for j in range(k+1,n):
          A[i][j] = m*A[k][j] + A[i][j]
        A[i][k] = 0    
    return (L, A) 

def formata_matriz(M):
    m = len(M)
    n = len(M[0])
    s = ""
    for i in range(m):
        for j in range(n):
           s += "%9.3f " % M[i][j]
        s += "\n"
    return s

(L, U) = fatoraLU(A)

Ml= np.array(L)
Mu= np.array(U)
print('Matriz L')
print(Ml)
print(' ')
print('Matriz U')
print(Mu)
print(' ')

def retroativas(A, b):
    n = len(A)
    x = n*[0] 
    for i in range(n-1, -1, -1):
      s = 0 
      for j in range(i+1, n):
        s = s + A[i][j]*x[j]
      x[i] = (b[i] - s)/A[i][i]
    return x

def sucessivas(A, b):
    n = len(A)
    x = n*[0]
    for i in range(0, n):
      s = 0     
      for j in range(0, i):
        s = s + A[i][j]*x[j]
      x[i] = (b[i] - s)/A[i][i]
    return x

def LUx(L,U,b):
    y = sucessivas(L, b) 
    x = retroativas(U, y)    
    return x

print('Portanto, temos:')
x = LUx(L,U,b)
for i in range(len(x)):
  print('Caminhão n° {} ={}'.format(i, "%9.3f "%x[i]) )